/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.daw1.wordle_goncalo.gui;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.daw1.wordle_goncalo.Motores.*;

/**
 *
 * @author Gonçalo
 */
public class ConfigMotorjDialog extends javax.swing.JDialog {

    private static final java.awt.Color COLOR_VERDE = Color.GREEN;
    private static final java.awt.Color COLOR_ROJO = Color.red;

    private String entrada;
    private final IMotorWordle motor;

    /**
     * Creates new form ConfigMotorjDialog
     *
     * @param parent
     * @param modal
     * @param motor
     */
    public ConfigMotorjDialog(java.awt.Frame parent, boolean modal, IMotorWordle motor) {
        super(parent, modal);
        this.motor = motor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gestionMotorjPanel2 = new javax.swing.JPanel();
        gestionMotorjLabel1 = new javax.swing.JLabel();
        altaPalabrajPanel3 = new javax.swing.JPanel();
        altajLabel2 = new javax.swing.JLabel();
        inputAltaPalabrajTextField1 = new javax.swing.JTextField();
        anadirPalabrajToggleButton1 = new javax.swing.JToggleButton();
        avisosAltaPalabrajLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bajajLabel3 = new javax.swing.JLabel();
        inputBajaPalabrajTextField2 = new javax.swing.JTextField();
        BorrarPalabrajToggleButton2 = new javax.swing.JToggleButton();
        avisosBajaPalabrajLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        gestionMotorjLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        gestionMotorjLabel1.setText("Gestión Motor");

        javax.swing.GroupLayout gestionMotorjPanel2Layout = new javax.swing.GroupLayout(gestionMotorjPanel2);
        gestionMotorjPanel2.setLayout(gestionMotorjPanel2Layout);
        gestionMotorjPanel2Layout.setHorizontalGroup(
            gestionMotorjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestionMotorjPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gestionMotorjLabel1)
                .addGap(83, 83, 83))
        );
        gestionMotorjPanel2Layout.setVerticalGroup(
            gestionMotorjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestionMotorjPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(gestionMotorjLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        altajLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        altajLabel2.setForeground(new java.awt.Color(0, 204, 0));
        altajLabel2.setText("Alta Palabra");

        anadirPalabrajToggleButton1.setText("Añadir");
        anadirPalabrajToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirPalabrajToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout altaPalabrajPanel3Layout = new javax.swing.GroupLayout(altaPalabrajPanel3);
        altaPalabrajPanel3.setLayout(altaPalabrajPanel3Layout);
        altaPalabrajPanel3Layout.setHorizontalGroup(
            altaPalabrajPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altaPalabrajPanel3Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(altaPalabrajPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avisosAltaPalabrajLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(altaPalabrajPanel3Layout.createSequentialGroup()
                        .addGroup(altaPalabrajPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(altajLabel2)
                            .addGroup(altaPalabrajPanel3Layout.createSequentialGroup()
                                .addComponent(inputAltaPalabrajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anadirPalabrajToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        altaPalabrajPanel3Layout.setVerticalGroup(
            altaPalabrajPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altaPalabrajPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(altajLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(altaPalabrajPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anadirPalabrajToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAltaPalabrajTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avisosAltaPalabrajLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bajajLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bajajLabel3.setForeground(new java.awt.Color(255, 51, 51));
        bajajLabel3.setText("Baja Palabra");

        inputBajaPalabrajTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBajaPalabrajTextField2ActionPerformed(evt);
            }
        });

        BorrarPalabrajToggleButton2.setText("Borrar");
        BorrarPalabrajToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarPalabrajToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avisosBajaPalabrajLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bajajLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(inputBajaPalabrajTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BorrarPalabrajToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(bajajLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BorrarPalabrajToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(inputBajaPalabrajTextField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avisosBajaPalabrajLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestionMotorjPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(altaPalabrajPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(gestionMotorjPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altaPalabrajPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputBajaPalabrajTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBajaPalabrajTextField2ActionPerformed
        //this.inputBajaPalabrajTextField2.getText();
    }//GEN-LAST:event_inputBajaPalabrajTextField2ActionPerformed

    private void BorrarPalabrajToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarPalabrajToggleButton2ActionPerformed
        this.avisosBajaPalabrajLabel2.setText("");
        entrada = this.inputBajaPalabrajTextField2.getText();
        if ((entrada).matches("[Ñña-zA-Z]{5}")) {
            if (motor.checkPalabra(entrada.toUpperCase())) {
                try {
                    motor.removePalabra(entrada.toUpperCase());
                } catch (SQLException ex) {
                    Logger.getLogger(ConfigMotorjDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.avisosBajaPalabrajLabel2.setForeground(COLOR_VERDE);
                this.avisosBajaPalabrajLabel2.setText("Palabra borrada correctamente");
            } else {
                this.avisosBajaPalabrajLabel2.setForeground(COLOR_ROJO);
                this.avisosBajaPalabrajLabel2.setText("Palabra no existe");
            }
        } else {
            this.avisosBajaPalabrajLabel2.setForeground(COLOR_ROJO);
            this.avisosBajaPalabrajLabel2.setText("¡La palabra debe estar compuesta por 5 letras!");
        }
    }//GEN-LAST:event_BorrarPalabrajToggleButton2ActionPerformed

    private void anadirPalabrajToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirPalabrajToggleButton1ActionPerformed
        this.avisosAltaPalabrajLabel1.setText("");
        entrada = this.inputAltaPalabrajTextField1.getText();
        if ((entrada).matches("[Ñña-zA-Z]{5}")) {
            if (!motor.checkPalabra(entrada.toUpperCase())) {
                try {
                    if (motor.getClass().getName().equalsIgnoreCase(org.daw1.wordle_goncalo.Motores.MotorBBDD.class.getName())) {
                        motor.anadirPalabra(entrada.toUpperCase());
                    } else {
                        motor.anadirPalabra("\n" + entrada.toUpperCase() + "\n");
                    }
                } catch (IOException | SQLException ex) {
                    Logger.getLogger(ConfigMotorjDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.avisosAltaPalabrajLabel1.setForeground(COLOR_VERDE);
                this.avisosAltaPalabrajLabel1.setText("¡Palabra añadida correctamente!");
            } else {
                this.avisosAltaPalabrajLabel1.setForeground(COLOR_ROJO);
                this.avisosAltaPalabrajLabel1.setText("¡La palabra ya existe intente con otra!");
            }
        } else {
            this.avisosAltaPalabrajLabel1.setForeground(COLOR_ROJO);
            this.avisosAltaPalabrajLabel1.setText("¡La palabra debe estar compuesta por 5 letras!");
        }
    }//GEN-LAST:event_anadirPalabrajToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigMotorjDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigMotorjDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigMotorjDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigMotorjDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfigMotorjDialog dialog = new ConfigMotorjDialog(new javax.swing.JFrame(), true, new MotorTest());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BorrarPalabrajToggleButton2;
    private javax.swing.JPanel altaPalabrajPanel3;
    private javax.swing.JLabel altajLabel2;
    private javax.swing.JToggleButton anadirPalabrajToggleButton1;
    private javax.swing.JLabel avisosAltaPalabrajLabel1;
    private javax.swing.JLabel avisosBajaPalabrajLabel2;
    private javax.swing.JLabel bajajLabel3;
    private javax.swing.JLabel gestionMotorjLabel1;
    private javax.swing.JPanel gestionMotorjPanel2;
    private javax.swing.JTextField inputAltaPalabrajTextField1;
    private javax.swing.JTextField inputBajaPalabrajTextField2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
