/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.daw1.wordle_goncalo.gui;

import org.daw1.wordle_goncalo.Motores.*;
import java.awt.Color;
import java.io.File;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Gonçalo
 */
public class MainJFrame extends javax.swing.JFrame {

    String mensaje;
    private Map<Character, Integer> letrasPorPalabra;
    private int contador = 0;//contador para saber con que fila estoy trabajando
    private IMotorWordle motor;
    private String palabra;
    private String entrada;

    private static final java.awt.Color COLOR_ROJO = Color.RED;//new java.awt.Color(64,64,64);
    private static final java.awt.Color COLOR_VERDE = new java.awt.Color(51, 255, 51);
    private static final java.awt.Color COLOR_AMARILLO = Color.YELLOW;//new java.awt.Color(255,255,102);

    public static final File file = new File(Path.of(".") + File.separator + "data" + File.separator + "archivo.txt");

    /**
     * Creates new form MainJFrame
     *
     * @param motor
     */
    public MainJFrame(IMotorWordle motor) {
        this.letrasPorPalabra = new LinkedHashMap<>();
        initComponents();
        this.motor = motor;
        this.palabra = motor.obtenerPalabraAleatoria().toUpperCase();
    }

    public MainJFrame() {
        this.letrasPorPalabra = new LinkedHashMap<>();
        initComponents();
        this.motor = new MotorTest();
        this.palabra = motor.obtenerPalabraAleatoria().toUpperCase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1buttonGroup1 = new javax.swing.ButtonGroup();
        MainjPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tecladojPanel = new javax.swing.JPanel();
        DosFilasTecladojPanel3 = new javax.swing.JPanel();
        qjButton1_1 = new javax.swing.JButton();
        wjButton1_2 = new javax.swing.JButton();
        ejButton1_3 = new javax.swing.JButton();
        rjButton1_4 = new javax.swing.JButton();
        tjButton1_5 = new javax.swing.JButton();
        yjButton1_6 = new javax.swing.JButton();
        ujButton1_7 = new javax.swing.JButton();
        ijButton1_8 = new javax.swing.JButton();
        ojButton1_9 = new javax.swing.JButton();
        pjButton1_10 = new javax.swing.JButton();
        ajButton2_1 = new javax.swing.JButton();
        sjButton2_2 = new javax.swing.JButton();
        djButton2_3 = new javax.swing.JButton();
        fjButton2_4 = new javax.swing.JButton();
        gjButton2_5 = new javax.swing.JButton();
        hjButton2_6 = new javax.swing.JButton();
        jjButton2_7 = new javax.swing.JButton();
        kjButton2_8 = new javax.swing.JButton();
        ljButton2_9 = new javax.swing.JButton();
        nnjButton2_10 = new javax.swing.JButton();
        zjButton1 = new javax.swing.JButton();
        xjButton2 = new javax.swing.JButton();
        cjButton3 = new javax.swing.JButton();
        vjButton4 = new javax.swing.JButton();
        bjButton5 = new javax.swing.JButton();
        njButton6 = new javax.swing.JButton();
        mjButton7 = new javax.swing.JButton();
        BorrarjButton8 = new javax.swing.JButton();
        nombrejLabel1 = new javax.swing.JLabel();
        letrasjPanel2 = new javax.swing.JPanel();
        a11jLabel1_1 = new javax.swing.JLabel();
        a12jLabel1_2 = new javax.swing.JLabel();
        a13jLabel1_3 = new javax.swing.JLabel();
        a14jLabel1_4 = new javax.swing.JLabel();
        a15jLabel1_5 = new javax.swing.JLabel();
        a21jLabel2_1 = new javax.swing.JLabel();
        a22jLabel2_2 = new javax.swing.JLabel();
        a23jLabel2_3 = new javax.swing.JLabel();
        a24jLabel2_4 = new javax.swing.JLabel();
        a25jLabel2_5 = new javax.swing.JLabel();
        a31jLabel3_1 = new javax.swing.JLabel();
        a32jLabel3_2 = new javax.swing.JLabel();
        a33jLabel3_3 = new javax.swing.JLabel();
        a34jLabel3_4 = new javax.swing.JLabel();
        a35jLabel3_5 = new javax.swing.JLabel();
        a41jLabel4_1 = new javax.swing.JLabel();
        a42jLabel4_2 = new javax.swing.JLabel();
        a43jLabel4_3 = new javax.swing.JLabel();
        a44jLabel4_4 = new javax.swing.JLabel();
        a45jLabel4_5 = new javax.swing.JLabel();
        a51jLabel5_1 = new javax.swing.JLabel();
        a52jLabel5_2 = new javax.swing.JLabel();
        a53jLabel5_3 = new javax.swing.JLabel();
        a54jLabel5_4 = new javax.swing.JLabel();
        a55jLabel5_5 = new javax.swing.JLabel();
        a61jLabel6_1 = new javax.swing.JLabel();
        a62jLabel6_2 = new javax.swing.JLabel();
        a63jLabel6_3 = new javax.swing.JLabel();
        a64jLabel6_4 = new javax.swing.JLabel();
        a65jLabel6_5 = new javax.swing.JLabel();
        inputjTextField1 = new javax.swing.JTextField();
        enviarjButton1 = new javax.swing.JButton();
        avisosjLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivojMenu1 = new javax.swing.JMenu();
        reiniciarjMenuItem1 = new javax.swing.JMenuItem();
        motoresjMenu2 = new javax.swing.JMenu();
        motorTestjRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        motorFicherojRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        motorBBDDESjRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        motorBBDDGAjRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        gestionMotorjMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        DosFilasTecladojPanel3.setLayout(new java.awt.GridLayout(2, 10));

        qjButton1_1.setText("Q");
        qjButton1_1.setMaximumSize(new java.awt.Dimension(24, 24));
        qjButton1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qjButton1_1ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(qjButton1_1);

        wjButton1_2.setText("W");
        wjButton1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wjButton1_2ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(wjButton1_2);

        ejButton1_3.setText("E");
        ejButton1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejButton1_3ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(ejButton1_3);

        rjButton1_4.setText("R");
        rjButton1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rjButton1_4ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(rjButton1_4);

        tjButton1_5.setText("T");
        tjButton1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjButton1_5ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(tjButton1_5);

        yjButton1_6.setText("Y");
        yjButton1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yjButton1_6ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(yjButton1_6);

        ujButton1_7.setText("U");
        ujButton1_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujButton1_7ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(ujButton1_7);

        ijButton1_8.setText("I");
        ijButton1_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ijButton1_8ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(ijButton1_8);

        ojButton1_9.setText("O");
        ojButton1_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ojButton1_9ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(ojButton1_9);

        pjButton1_10.setText("P");
        pjButton1_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjButton1_10ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(pjButton1_10);

        ajButton2_1.setText("A");
        ajButton2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajButton2_1ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(ajButton2_1);

        sjButton2_2.setText("S");
        sjButton2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sjButton2_2ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(sjButton2_2);

        djButton2_3.setText("D");
        djButton2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                djButton2_3ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(djButton2_3);

        fjButton2_4.setText("F");
        fjButton2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fjButton2_4ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(fjButton2_4);

        gjButton2_5.setText("G");
        gjButton2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gjButton2_5ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(gjButton2_5);

        hjButton2_6.setText("H");
        hjButton2_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hjButton2_6ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(hjButton2_6);

        jjButton2_7.setText("J");
        jjButton2_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjButton2_7ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(jjButton2_7);

        kjButton2_8.setText("K");
        kjButton2_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kjButton2_8ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(kjButton2_8);

        ljButton2_9.setText("L");
        ljButton2_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ljButton2_9ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(ljButton2_9);

        nnjButton2_10.setText("Ñ");
        nnjButton2_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nnjButton2_10ActionPerformed(evt);
            }
        });
        DosFilasTecladojPanel3.add(nnjButton2_10);

        zjButton1.setText("Z");
        zjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zjButton1ActionPerformed(evt);
            }
        });

        xjButton2.setText("X");
        xjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xjButton2ActionPerformed(evt);
            }
        });

        cjButton3.setText("C");
        cjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjButton3ActionPerformed(evt);
            }
        });

        vjButton4.setText("V");
        vjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vjButton4ActionPerformed(evt);
            }
        });

        bjButton5.setText("B");
        bjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bjButton5ActionPerformed(evt);
            }
        });

        njButton6.setText("N");
        njButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                njButton6ActionPerformed(evt);
            }
        });

        mjButton7.setText("M");
        mjButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mjButton7ActionPerformed(evt);
            }
        });

        BorrarjButton8.setText("Borrar");
        BorrarjButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarjButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tecladojPanelLayout = new javax.swing.GroupLayout(tecladojPanel);
        tecladojPanel.setLayout(tecladojPanelLayout);
        tecladojPanelLayout.setHorizontalGroup(
            tecladojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tecladojPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(tecladojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DosFilasTecladojPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tecladojPanelLayout.createSequentialGroup()
                        .addComponent(zjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(xjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(cjButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(vjButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(bjButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(njButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(mjButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(BorrarjButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tecladojPanelLayout.setVerticalGroup(
            tecladojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tecladojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DosFilasTecladojPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(tecladojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tecladojPanelLayout.createSequentialGroup()
                        .addGroup(tecladojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zjButton1)
                            .addComponent(xjButton2)
                            .addComponent(cjButton3)
                            .addComponent(vjButton4)
                            .addComponent(bjButton5)
                            .addComponent(njButton6)
                            .addComponent(mjButton7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BorrarjButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        nombrejLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        nombrejLabel1.setText("WORDLE");

        letrasjPanel2.setLayout(new java.awt.GridLayout(6, 5));

        a11jLabel1_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel1_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel1_1.setText("-");
        letrasjPanel2.add(a11jLabel1_1);

        a12jLabel1_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a12jLabel1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a12jLabel1_2.setText("-");
        letrasjPanel2.add(a12jLabel1_2);

        a13jLabel1_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a13jLabel1_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a13jLabel1_3.setText("-");
        letrasjPanel2.add(a13jLabel1_3);

        a14jLabel1_4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a14jLabel1_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a14jLabel1_4.setText("-");
        letrasjPanel2.add(a14jLabel1_4);

        a15jLabel1_5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a15jLabel1_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a15jLabel1_5.setText("-");
        letrasjPanel2.add(a15jLabel1_5);

        a21jLabel2_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a21jLabel2_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a21jLabel2_1.setText("-");
        letrasjPanel2.add(a21jLabel2_1);

        a22jLabel2_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a22jLabel2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a22jLabel2_2.setText("-");
        letrasjPanel2.add(a22jLabel2_2);

        a23jLabel2_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a23jLabel2_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a23jLabel2_3.setText("-");
        letrasjPanel2.add(a23jLabel2_3);

        a24jLabel2_4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a24jLabel2_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a24jLabel2_4.setText("-");
        letrasjPanel2.add(a24jLabel2_4);

        a25jLabel2_5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a25jLabel2_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a25jLabel2_5.setText("-");
        letrasjPanel2.add(a25jLabel2_5);

        a31jLabel3_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a31jLabel3_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a31jLabel3_1.setText("-");
        letrasjPanel2.add(a31jLabel3_1);

        a32jLabel3_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a32jLabel3_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a32jLabel3_2.setText("-");
        letrasjPanel2.add(a32jLabel3_2);

        a33jLabel3_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a33jLabel3_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a33jLabel3_3.setText("-");
        letrasjPanel2.add(a33jLabel3_3);

        a34jLabel3_4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a34jLabel3_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a34jLabel3_4.setText("-");
        letrasjPanel2.add(a34jLabel3_4);

        a35jLabel3_5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a35jLabel3_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a35jLabel3_5.setText("-");
        letrasjPanel2.add(a35jLabel3_5);

        a41jLabel4_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a41jLabel4_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a41jLabel4_1.setText("-");
        letrasjPanel2.add(a41jLabel4_1);

        a42jLabel4_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a42jLabel4_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a42jLabel4_2.setText("-");
        letrasjPanel2.add(a42jLabel4_2);

        a43jLabel4_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a43jLabel4_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a43jLabel4_3.setText("-");
        letrasjPanel2.add(a43jLabel4_3);

        a44jLabel4_4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a44jLabel4_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a44jLabel4_4.setText("-");
        letrasjPanel2.add(a44jLabel4_4);

        a45jLabel4_5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a45jLabel4_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a45jLabel4_5.setText("-");
        letrasjPanel2.add(a45jLabel4_5);

        a51jLabel5_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a51jLabel5_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a51jLabel5_1.setText("-");
        letrasjPanel2.add(a51jLabel5_1);

        a52jLabel5_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a52jLabel5_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a52jLabel5_2.setText("-");
        letrasjPanel2.add(a52jLabel5_2);

        a53jLabel5_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a53jLabel5_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a53jLabel5_3.setText("-");
        letrasjPanel2.add(a53jLabel5_3);

        a54jLabel5_4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a54jLabel5_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a54jLabel5_4.setText("-");
        letrasjPanel2.add(a54jLabel5_4);

        a55jLabel5_5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a55jLabel5_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a55jLabel5_5.setText("-");
        letrasjPanel2.add(a55jLabel5_5);

        a61jLabel6_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a61jLabel6_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a61jLabel6_1.setText("-");
        letrasjPanel2.add(a61jLabel6_1);

        a62jLabel6_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a62jLabel6_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a62jLabel6_2.setText("-");
        letrasjPanel2.add(a62jLabel6_2);

        a63jLabel6_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a63jLabel6_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a63jLabel6_3.setText("-");
        letrasjPanel2.add(a63jLabel6_3);

        a64jLabel6_4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a64jLabel6_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a64jLabel6_4.setText("-");
        letrasjPanel2.add(a64jLabel6_4);

        a65jLabel6_5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a65jLabel6_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a65jLabel6_5.setText("-");
        letrasjPanel2.add(a65jLabel6_5);

        inputjTextField1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        inputjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputjTextField1ActionPerformed(evt);
            }
        });

        enviarjButton1.setText("Enviar");
        enviarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarjButton1ActionPerformed(evt);
            }
        });

        avisosjLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        avisosjLabel1.setText(mensaje);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(nombrejLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(letrasjPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avisosjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enviarjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(tecladojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(nombrejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letrasjPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputjTextField1)
                    .addComponent(enviarjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avisosjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(427, 427, 427)
                    .addComponent(tecladojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout MainjPanelLayout = new javax.swing.GroupLayout(MainjPanel);
        MainjPanel.setLayout(MainjPanelLayout);
        MainjPanelLayout.setHorizontalGroup(
            MainjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainjPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        MainjPanelLayout.setVerticalGroup(
            MainjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        archivojMenu1.setText("Archivo");

        reiniciarjMenuItem1.setText("Nueva Partida");
        reiniciarjMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarjMenuItem1ActionPerformed(evt);
            }
        });
        archivojMenu1.add(reiniciarjMenuItem1);

        jMenuBar1.add(archivojMenu1);

        motoresjMenu2.setText("Motores");

        grupo1buttonGroup1.add(motorTestjRadioButtonMenuItem1);
        motorTestjRadioButtonMenuItem1.setSelected(true);
        motorTestjRadioButtonMenuItem1.setText("Motor Test");
        motorTestjRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorTestjRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        motoresjMenu2.add(motorTestjRadioButtonMenuItem1);

        grupo1buttonGroup1.add(motorFicherojRadioButtonMenuItem2);
        motorFicherojRadioButtonMenuItem2.setText("Motor Fichero");
        motorFicherojRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorFicherojRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        motoresjMenu2.add(motorFicherojRadioButtonMenuItem2);

        grupo1buttonGroup1.add(motorBBDDESjRadioButtonMenuItem3);
        motorBBDDESjRadioButtonMenuItem3.setText("Motor BBDD (Español)");
        motoresjMenu2.add(motorBBDDESjRadioButtonMenuItem3);

        grupo1buttonGroup1.add(motorBBDDGAjRadioButtonMenuItem4);
        motorBBDDGAjRadioButtonMenuItem4.setText("Motor BBDD (Galego)");
        motoresjMenu2.add(motorBBDDGAjRadioButtonMenuItem4);

        gestionMotorjMenuItem1.setText("Administrar Motor");
        gestionMotorjMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionMotorjMenuItem1ActionPerformed(evt);
            }
        });
        motoresjMenu2.add(gestionMotorjMenuItem1);

        jMenuBar1.add(motoresjMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(MainjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputjTextField1ActionPerformed
        //this.inputjTextField1
    }//GEN-LAST:event_inputjTextField1ActionPerformed

    private void BorrarjButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarjButton8ActionPerformed
        entrada = this.inputjTextField1.getText();
        if (entrada.length() >= 1) {
            StringBuilder sb = new StringBuilder(entrada);
            sb.deleteCharAt(entrada.length() - 1);
            this.inputjTextField1.setText(sb.toString());
        }
    }//GEN-LAST:event_BorrarjButton8ActionPerformed

    private void njButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_njButton6ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "N");
    }//GEN-LAST:event_njButton6ActionPerformed

    private void vjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vjButton4ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "N");
    }//GEN-LAST:event_vjButton4ActionPerformed

    private void qjButton1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qjButton1_1ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "Q");
    }//GEN-LAST:event_qjButton1_1ActionPerformed

    private void enviarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarjButton1ActionPerformed
        switch (contador) {
            case 0:
                printearFila(a11jLabel1_1, a12jLabel1_2, a13jLabel1_3, a14jLabel1_4, a15jLabel1_5);
                break;
            case 1:
                printearFila(a21jLabel2_1, a22jLabel2_2, a23jLabel2_3, a24jLabel2_4, a25jLabel2_5);
                break;
            case 2:
                printearFila(a31jLabel3_1, a32jLabel3_2, a33jLabel3_3, a34jLabel3_4, a35jLabel3_5);
                break;
            case 3:
                printearFila(a41jLabel4_1, a42jLabel4_2, a43jLabel4_3, a44jLabel4_4, a45jLabel4_5);
                break;
            case 4:
                printearFila(a51jLabel5_1, a52jLabel5_2, a53jLabel5_3, a54jLabel5_4, a55jLabel5_5);
                break;
            case 5:
                printearFila(a61jLabel6_1, a62jLabel6_2, a63jLabel6_3, a64jLabel6_4, a65jLabel6_5);
                break;
            default:
                break;
        }
        if (ganarJuego()) {
            this.avisosjLabel1.setText("¡Ganaste en " + contador + (contador == 1 ? " intento!" : " intentos!"));
            this.avisosjLabel1.setForeground(COLOR_VERDE);
            this.enviarjButton1.setEnabled(false);
            contador = 7;
        } else if (contador == 6) {
            this.avisosjLabel1.setText("¡Perdiste la palabra era " + this.palabra + "!");
            this.avisosjLabel1.setForeground(COLOR_ROJO);
            this.enviarjButton1.setEnabled(false);
        }
    }//GEN-LAST:event_enviarjButton1ActionPerformed

    private void printearFila(JLabel j1, JLabel j2, JLabel j3, JLabel j4, JLabel j5) {
        entrada = this.inputjTextField1.getText().toUpperCase();
        if (entrada.matches("[Ñña-zA-Z]{5}")) {
            if (motor.checkPalabra(entrada)) {
                this.avisosjLabel1.setText("");
                contarLetrasCorrectas();
                checkFila(j1, 0);
                checkFila(j2, 1);
                checkFila(j3, 2);
                checkFila(j4, 3);
                checkFila(j5, 4);
                contador++;
            } else {
                this.avisosjLabel1.setText("La palabra no existe");
                this.avisosjLabel1.setForeground(COLOR_ROJO);
            }
        } else {
            this.avisosjLabel1.setText("¡La palabra debe estar compuesta por 5 letras!");
            this.avisosjLabel1.setForeground(COLOR_ROJO);
        }
    }

    private void wjButton1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wjButton1_2ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "W");
    }//GEN-LAST:event_wjButton1_2ActionPerformed

    private void ejButton1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejButton1_3ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "E");
    }//GEN-LAST:event_ejButton1_3ActionPerformed

    private void rjButton1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rjButton1_4ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "R");
    }//GEN-LAST:event_rjButton1_4ActionPerformed

    private void tjButton1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjButton1_5ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "T");
    }//GEN-LAST:event_tjButton1_5ActionPerformed

    private void yjButton1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yjButton1_6ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "Y");
    }//GEN-LAST:event_yjButton1_6ActionPerformed

    private void ujButton1_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujButton1_7ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "U");
    }//GEN-LAST:event_ujButton1_7ActionPerformed

    private void ijButton1_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ijButton1_8ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "I");
    }//GEN-LAST:event_ijButton1_8ActionPerformed

    private void ojButton1_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ojButton1_9ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "O");
    }//GEN-LAST:event_ojButton1_9ActionPerformed

    private void pjButton1_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjButton1_10ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "P");
    }//GEN-LAST:event_pjButton1_10ActionPerformed

    private void ajButton2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajButton2_1ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "A");
    }//GEN-LAST:event_ajButton2_1ActionPerformed

    private void sjButton2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sjButton2_2ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "S");
    }//GEN-LAST:event_sjButton2_2ActionPerformed

    private void djButton2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_djButton2_3ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "D");
    }//GEN-LAST:event_djButton2_3ActionPerformed

    private void fjButton2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fjButton2_4ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "F");
    }//GEN-LAST:event_fjButton2_4ActionPerformed

    private void gjButton2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gjButton2_5ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "G");
    }//GEN-LAST:event_gjButton2_5ActionPerformed

    private void hjButton2_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hjButton2_6ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "H");
    }//GEN-LAST:event_hjButton2_6ActionPerformed

    private void jjButton2_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjButton2_7ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "J");
    }//GEN-LAST:event_jjButton2_7ActionPerformed

    private void kjButton2_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kjButton2_8ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "K");
    }//GEN-LAST:event_kjButton2_8ActionPerformed

    private void ljButton2_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ljButton2_9ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "L");
    }//GEN-LAST:event_ljButton2_9ActionPerformed

    private void nnjButton2_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nnjButton2_10ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "Ñ");
    }//GEN-LAST:event_nnjButton2_10ActionPerformed

    private void zjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zjButton1ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "Z");
    }//GEN-LAST:event_zjButton1ActionPerformed

    private void xjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xjButton2ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "X");
    }//GEN-LAST:event_xjButton2ActionPerformed

    private void cjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjButton3ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "C");
    }//GEN-LAST:event_cjButton3ActionPerformed

    private void bjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjButton5ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "B");
    }//GEN-LAST:event_bjButton5ActionPerformed

    private void mjButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mjButton7ActionPerformed
        entrada = this.inputjTextField1.getText();
        this.inputjTextField1.setText(entrada + "M");
    }//GEN-LAST:event_mjButton7ActionPerformed

    private void reiniciarjMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarjMenuItem1ActionPerformed
        resetProgram();
    }//GEN-LAST:event_reiniciarjMenuItem1ActionPerformed

    private void resetProgram() {
        for (Object label : this.letrasjPanel2.getComponents()) {
            ((javax.swing.JLabel) label).setText("-");
            ((javax.swing.JLabel) label).setForeground(new java.awt.Color(51, 51, 51));
        }
        for (Object boton : this.DosFilasTecladojPanel3.getComponents()) {
            ((javax.swing.JButton) boton).setBackground(new java.awt.Color(238, 238, 238));
        }
        this.zjButton1.setBackground(new java.awt.Color(238, 238, 238));
        this.xjButton2.setBackground(new java.awt.Color(238, 238, 238));
        this.cjButton3.setBackground(new java.awt.Color(238, 238, 238));
        this.vjButton4.setBackground(new java.awt.Color(238, 238, 238));
        this.bjButton5.setBackground(new java.awt.Color(238, 238, 238));
        this.njButton6.setBackground(new java.awt.Color(238, 238, 238));
        this.mjButton7.setBackground(new java.awt.Color(238, 238, 238));
        this.BorrarjButton8.setBackground(new java.awt.Color(238, 238, 238));
        contador = 0;
        this.letrasPorPalabra = new LinkedHashMap<>();
        entrada = "";
        palabra = motor.obtenerPalabraAleatoria().toUpperCase();
        this.avisosjLabel1.setText("");
        this.inputjTextField1.setText("");
        this.enviarjButton1.setEnabled(true);
    }

    private void gestionMotorjMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionMotorjMenuItem1ActionPerformed
        ConfigMotorjDialog gestionMotor = new ConfigMotorjDialog(this, true, motor);
        gestionMotor.setVisible(true);
        resetProgram();
    }//GEN-LAST:event_gestionMotorjMenuItem1ActionPerformed

    private void motorTestjRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorTestjRadioButtonMenuItem1ActionPerformed
        if (this.motorTestjRadioButtonMenuItem1.isSelected()) {
            motor = new MotorTest();
        }
        resetProgram();
    }//GEN-LAST:event_motorTestjRadioButtonMenuItem1ActionPerformed

    private void motorFicherojRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorFicherojRadioButtonMenuItem2ActionPerformed
        if (this.motorFicherojRadioButtonMenuItem2.isSelected()) {
            motor = new MotorFichero(file);
        }
        resetProgram();
    }//GEN-LAST:event_motorFicherojRadioButtonMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarjButton8;
    private javax.swing.JPanel DosFilasTecladojPanel3;
    private javax.swing.JPanel MainjPanel;
    private javax.swing.JLabel a11jLabel1_1;
    private javax.swing.JLabel a12jLabel1_2;
    private javax.swing.JLabel a13jLabel1_3;
    private javax.swing.JLabel a14jLabel1_4;
    private javax.swing.JLabel a15jLabel1_5;
    private javax.swing.JLabel a21jLabel2_1;
    private javax.swing.JLabel a22jLabel2_2;
    private javax.swing.JLabel a23jLabel2_3;
    private javax.swing.JLabel a24jLabel2_4;
    private javax.swing.JLabel a25jLabel2_5;
    private javax.swing.JLabel a31jLabel3_1;
    private javax.swing.JLabel a32jLabel3_2;
    private javax.swing.JLabel a33jLabel3_3;
    private javax.swing.JLabel a34jLabel3_4;
    private javax.swing.JLabel a35jLabel3_5;
    private javax.swing.JLabel a41jLabel4_1;
    private javax.swing.JLabel a42jLabel4_2;
    private javax.swing.JLabel a43jLabel4_3;
    private javax.swing.JLabel a44jLabel4_4;
    private javax.swing.JLabel a45jLabel4_5;
    private javax.swing.JLabel a51jLabel5_1;
    private javax.swing.JLabel a52jLabel5_2;
    private javax.swing.JLabel a53jLabel5_3;
    private javax.swing.JLabel a54jLabel5_4;
    private javax.swing.JLabel a55jLabel5_5;
    private javax.swing.JLabel a61jLabel6_1;
    private javax.swing.JLabel a62jLabel6_2;
    private javax.swing.JLabel a63jLabel6_3;
    private javax.swing.JLabel a64jLabel6_4;
    private javax.swing.JLabel a65jLabel6_5;
    private javax.swing.JButton ajButton2_1;
    private javax.swing.JMenu archivojMenu1;
    private javax.swing.JLabel avisosjLabel1;
    private javax.swing.JButton bjButton5;
    private javax.swing.JButton cjButton3;
    private javax.swing.JButton djButton2_3;
    private javax.swing.JButton ejButton1_3;
    private javax.swing.JButton enviarjButton1;
    private javax.swing.JButton fjButton2_4;
    private javax.swing.JMenuItem gestionMotorjMenuItem1;
    private javax.swing.JButton gjButton2_5;
    private javax.swing.ButtonGroup grupo1buttonGroup1;
    private javax.swing.JButton hjButton2_6;
    private javax.swing.JButton ijButton1_8;
    private javax.swing.JTextField inputjTextField1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jjButton2_7;
    private javax.swing.JButton kjButton2_8;
    private javax.swing.JPanel letrasjPanel2;
    private javax.swing.JButton ljButton2_9;
    private javax.swing.JButton mjButton7;
    private javax.swing.JRadioButtonMenuItem motorBBDDESjRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem motorBBDDGAjRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem motorFicherojRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem motorTestjRadioButtonMenuItem1;
    private javax.swing.JMenu motoresjMenu2;
    private javax.swing.JButton njButton6;
    private javax.swing.JButton nnjButton2_10;
    private javax.swing.JLabel nombrejLabel1;
    private javax.swing.JButton ojButton1_9;
    private javax.swing.JButton pjButton1_10;
    private javax.swing.JButton qjButton1_1;
    private javax.swing.JMenuItem reiniciarjMenuItem1;
    private javax.swing.JButton rjButton1_4;
    private javax.swing.JButton sjButton2_2;
    private javax.swing.JPanel tecladojPanel;
    private javax.swing.JButton tjButton1_5;
    private javax.swing.JButton ujButton1_7;
    private javax.swing.JButton vjButton4;
    private javax.swing.JButton wjButton1_2;
    private javax.swing.JButton xjButton2;
    private javax.swing.JButton yjButton1_6;
    private javax.swing.JButton zjButton1;
    // End of variables declaration//GEN-END:variables

    private void checkFila(JLabel j, int numero_letra) {
        if ((entrada.charAt(numero_letra) + "").equalsIgnoreCase(palabra.charAt(numero_letra) + "")) {
            j.setText(entrada.charAt(numero_letra) + "");
            j.setForeground(COLOR_VERDE);
            pintarTeclado(entrada.charAt(numero_letra) + "").setBackground(COLOR_VERDE);

        } else if ((palabra).contains(entrada.charAt(numero_letra) + "")) {
            j.setText(entrada.charAt(numero_letra) + "");
            if (letrasPorPalabra.get(entrada.charAt(numero_letra)) != 0) {
                j.setForeground(COLOR_AMARILLO);
                if (pintarTeclado(entrada.charAt(numero_letra) + "").getBackground() != COLOR_VERDE) {
                    pintarTeclado(entrada.charAt(numero_letra) + "").setBackground(COLOR_AMARILLO);
                }
                letrasPorPalabra.put(entrada.charAt(numero_letra), letrasPorPalabra.get(entrada.charAt(numero_letra)) - 1);
            } else {
                j.setForeground(COLOR_ROJO);
                if (pintarTeclado(entrada.charAt(numero_letra) + "").getBackground() != COLOR_VERDE && pintarTeclado(entrada.charAt(numero_letra) + "").getBackground() != COLOR_AMARILLO) {
                    pintarTeclado(entrada.charAt(numero_letra) + "").setBackground(COLOR_ROJO);
                }
            }
        } else {
            j.setText(entrada.charAt(numero_letra) + "");
            j.setForeground(COLOR_ROJO);
            if (pintarTeclado(entrada.charAt(numero_letra) + "").getBackground() != COLOR_VERDE && pintarTeclado(entrada.charAt(numero_letra) + "").getBackground() != COLOR_AMARILLO) {
                pintarTeclado(entrada.charAt(numero_letra) + "").setBackground(COLOR_ROJO);
            }
        }
    }

    public boolean ganarJuego() {
        if (entrada.matches("[a-zA-Z]{5}")) {
            return (entrada.charAt(0) + "").equalsIgnoreCase(palabra.charAt(0) + "") && (entrada.charAt(1) + "").equalsIgnoreCase(palabra.charAt(1) + "") && (entrada.charAt(2) + "").equalsIgnoreCase(palabra.charAt(2) + "") && (entrada.charAt(3) + "").equalsIgnoreCase(palabra.charAt(3) + "") && (entrada.charAt(4) + "").equalsIgnoreCase(palabra.charAt(4) + "");
        } else {
            return false;
        }

    }

    public void contarLetrasCorrectas() {
        for (int i = 0; i < palabra.length(); i++) {//contar cuantas letras de cada hay en la palabra
            if (!letrasPorPalabra.containsKey(palabra.charAt(i))) {
                letrasPorPalabra.put(palabra.charAt(i), 1);
            } else {
                letrasPorPalabra.put(palabra.charAt(i), (letrasPorPalabra.get(palabra.charAt(i))) + 1);
            }
        }
        for (int i = 0; i < entrada.length(); i++) {//contar cuantas letras estan bien colocadas 
            if ((entrada.charAt(i) + "").equalsIgnoreCase(palabra.charAt(i) + "")) {
                letrasPorPalabra.put(palabra.charAt(i), (letrasPorPalabra.get(palabra.charAt(i))) - 1);
            }
        }
    }

    public JButton pintarTeclado(String c) {
        JButton[] botones = {qjButton1_1, wjButton1_2, ejButton1_3, rjButton1_4, tjButton1_5, yjButton1_6, ujButton1_7, ijButton1_8, ojButton1_9, pjButton1_10, ajButton2_1, sjButton2_2, djButton2_3, fjButton2_4, gjButton2_5, hjButton2_6, jjButton2_7, kjButton2_8, ljButton2_9, nnjButton2_10, zjButton1, xjButton2, cjButton3, vjButton4, bjButton5, njButton6, mjButton7};
        for (JButton boton : botones) {
            if (((boton.getText())).equalsIgnoreCase(c)) {
                return boton;
            }
        }
        return botones[0];
    }
}
