/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wordle_goncalo.gui;

/**
 *
 * @author Gonçalo
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enviarjButton1 = new javax.swing.JButton();
        nombrejLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        a11jLabel1_1 = new javax.swing.JLabel();
        a11jLabel1_2 = new javax.swing.JLabel();
        a11jLabel1_3 = new javax.swing.JLabel();
        a11jLabel1_4 = new javax.swing.JLabel();
        a11jLabel1_5 = new javax.swing.JLabel();
        a11jLabel1_6 = new javax.swing.JLabel();
        a11jLabel2_1 = new javax.swing.JLabel();
        a11jLabel2_2 = new javax.swing.JLabel();
        a11jLabel2_3 = new javax.swing.JLabel();
        a11jLabel2_4 = new javax.swing.JLabel();
        a11jLabel2_5 = new javax.swing.JLabel();
        a11jLabel2_6 = new javax.swing.JLabel();
        a11jLabel3_1 = new javax.swing.JLabel();
        a11jLabel3_2 = new javax.swing.JLabel();
        a11jLabel3_3 = new javax.swing.JLabel();
        a11jLabel3_4 = new javax.swing.JLabel();
        a11jLabel3_5 = new javax.swing.JLabel();
        a11jLabel3_6 = new javax.swing.JLabel();
        a11jLabel4_1 = new javax.swing.JLabel();
        a11jLabel4_2 = new javax.swing.JLabel();
        a11jLabel4_3 = new javax.swing.JLabel();
        a11jLabel4_4 = new javax.swing.JLabel();
        a11jLabel4_5 = new javax.swing.JLabel();
        a11jLabel4_6 = new javax.swing.JLabel();
        a11jLabel5_1 = new javax.swing.JLabel();
        a11jLabel5_2 = new javax.swing.JLabel();
        a11jLabel5_3 = new javax.swing.JLabel();
        a11jLabel5_4 = new javax.swing.JLabel();
        a11jLabel5_5 = new javax.swing.JLabel();
        a11jLabel5_6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        enviarjButton1.setText("Enviar");

        nombrejLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        nombrejLabel1.setText("WORDLE");

        jPanel2.setLayout(new java.awt.GridLayout(6, 5));

        a11jLabel1_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel1_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel1_1.setText("-");
        jPanel2.add(a11jLabel1_1);

        a11jLabel1_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel1_2.setText("-");
        jPanel2.add(a11jLabel1_2);

        a11jLabel1_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel1_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel1_3.setText("-");
        jPanel2.add(a11jLabel1_3);

        a11jLabel1_4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel1_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel1_4.setText("-");
        jPanel2.add(a11jLabel1_4);

        a11jLabel1_5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel1_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel1_5.setText("-");
        jPanel2.add(a11jLabel1_5);

        a11jLabel1_6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel1_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel1_6.setText("-");
        jPanel2.add(a11jLabel1_6);

        a11jLabel2_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel2_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel2_1.setText("-");
        jPanel2.add(a11jLabel2_1);

        a11jLabel2_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel2_2.setText("-");
        jPanel2.add(a11jLabel2_2);

        a11jLabel2_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel2_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel2_3.setText("-");
        jPanel2.add(a11jLabel2_3);

        a11jLabel2_4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel2_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel2_4.setText("-");
        jPanel2.add(a11jLabel2_4);

        a11jLabel2_5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel2_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel2_5.setText("-");
        jPanel2.add(a11jLabel2_5);

        a11jLabel2_6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel2_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel2_6.setText("-");
        jPanel2.add(a11jLabel2_6);

        a11jLabel3_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel3_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel3_1.setText("-");
        jPanel2.add(a11jLabel3_1);

        a11jLabel3_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel3_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel3_2.setText("-");
        jPanel2.add(a11jLabel3_2);

        a11jLabel3_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel3_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel3_3.setText("-");
        jPanel2.add(a11jLabel3_3);

        a11jLabel3_4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel3_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel3_4.setText("-");
        jPanel2.add(a11jLabel3_4);

        a11jLabel3_5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel3_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel3_5.setText("-");
        jPanel2.add(a11jLabel3_5);

        a11jLabel3_6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel3_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel3_6.setText("-");
        jPanel2.add(a11jLabel3_6);

        a11jLabel4_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel4_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel4_1.setText("-");
        jPanel2.add(a11jLabel4_1);

        a11jLabel4_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel4_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel4_2.setText("-");
        jPanel2.add(a11jLabel4_2);

        a11jLabel4_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel4_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel4_3.setText("-");
        jPanel2.add(a11jLabel4_3);

        a11jLabel4_4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel4_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel4_4.setText("-");
        jPanel2.add(a11jLabel4_4);

        a11jLabel4_5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel4_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel4_5.setText("-");
        jPanel2.add(a11jLabel4_5);

        a11jLabel4_6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel4_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel4_6.setText("-");
        jPanel2.add(a11jLabel4_6);

        a11jLabel5_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel5_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel5_1.setText("-");
        jPanel2.add(a11jLabel5_1);

        a11jLabel5_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel5_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel5_2.setText("-");
        jPanel2.add(a11jLabel5_2);

        a11jLabel5_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel5_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel5_3.setText("-");
        jPanel2.add(a11jLabel5_3);

        a11jLabel5_4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel5_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel5_4.setText("-");
        jPanel2.add(a11jLabel5_4);

        a11jLabel5_5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel5_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel5_5.setText("-");
        jPanel2.add(a11jLabel5_5);

        a11jLabel5_6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        a11jLabel5_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11jLabel5_6.setText("-");
        jPanel2.add(a11jLabel5_6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(enviarjButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nombrejLabel1)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(nombrejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(enviarjButton1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a11jLabel1_1;
    private javax.swing.JLabel a11jLabel1_2;
    private javax.swing.JLabel a11jLabel1_3;
    private javax.swing.JLabel a11jLabel1_4;
    private javax.swing.JLabel a11jLabel1_5;
    private javax.swing.JLabel a11jLabel1_6;
    private javax.swing.JLabel a11jLabel2_1;
    private javax.swing.JLabel a11jLabel2_2;
    private javax.swing.JLabel a11jLabel2_3;
    private javax.swing.JLabel a11jLabel2_4;
    private javax.swing.JLabel a11jLabel2_5;
    private javax.swing.JLabel a11jLabel2_6;
    private javax.swing.JLabel a11jLabel3_1;
    private javax.swing.JLabel a11jLabel3_2;
    private javax.swing.JLabel a11jLabel3_3;
    private javax.swing.JLabel a11jLabel3_4;
    private javax.swing.JLabel a11jLabel3_5;
    private javax.swing.JLabel a11jLabel3_6;
    private javax.swing.JLabel a11jLabel4_1;
    private javax.swing.JLabel a11jLabel4_2;
    private javax.swing.JLabel a11jLabel4_3;
    private javax.swing.JLabel a11jLabel4_4;
    private javax.swing.JLabel a11jLabel4_5;
    private javax.swing.JLabel a11jLabel4_6;
    private javax.swing.JLabel a11jLabel5_1;
    private javax.swing.JLabel a11jLabel5_2;
    private javax.swing.JLabel a11jLabel5_3;
    private javax.swing.JLabel a11jLabel5_4;
    private javax.swing.JLabel a11jLabel5_5;
    private javax.swing.JLabel a11jLabel5_6;
    private javax.swing.JButton enviarjButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombrejLabel1;
    // End of variables declaration//GEN-END:variables
}
